@startuml Сompleting exercise
title Activity: Сompleting exercise 
start

:Бот выдает вопрос.
Кнопку подсказка.
Поле ответа;
note right: на каждой кнопке написан текст ответа;
repeat : Бот выдает Набор кнопок для составления ответа(3х3);
   
repeat :Пользователь выбирает кнопку;

backward :Кнопка выбранного ответа становится красной;
repeat while (Коректно?) is (Нет) not (Да)

backward :Текст с кнопки добавляется в поле ответа;
repeat while (ответ построен полностью) is (Нет) not (Да)
    
:Бот выдает кнопку перейти к следующему заданию;   

:Пользователь нажимает перейти к следующему заданию; 

stop


@enduml