@startuml
title Sequence Diagram: Сompleting exercise

actor User as U
participant "Bot" as B
database "RDBMS" as DB

== Создание вопроса ==
U -> B: выбор уровня упражнения
B -> DB: Запросить случайный вопрос из набора вопросов для данного уровня упражнения
B <- DB: Получить случайный вопрос из набора вопросов для данного уровня упражнения
U <- B: Вывести вопрос
U <- B: Вывести кнопку подсказки
B -> DB: Запросить набор ответов для данного вопроса
B -> DB: получить набор ответов для данного вопроса
U <- B: Вывести панель кнопок с ответами на текущую часть вопроса

== Пользователь выбирает ответ ==

alt Выбор кнопки с правильным ответом
U -> B: выбрал кнопку с правильным ответом
U <- B: вывод правильной части ответа с кнопки в поле ответа
U <- B: Вывести панель кнопок с ответами на следующую часть вопроса
else Выбор кнопки с не правильным ответом
U -> B: выбрал кнопку с не правильным ответом
U <- B: цвет выбранной кнопки становится красной   
end
== последний правильный ответ для данного вопроса ==
U -> B: выбрал кнопку с правильным ответом и это последний правильный ответ
U <- B: цвет поля ответа становится зеленым
U <- B: Добавляется кнопка перехода к следующему вопросу
== нажал кнопку подсказки ==
U -> B: выбрал кнопку подсказки
U <- B: кнопка с правильным ответом становится зеленой
== нажал кнопку выйти из упражнения ==
U -> B: выбрал кнопку выйти из упражнения
U <- B: возврат в главное меню бота


@enduml
