@startuml UserCaseMain

actor Administrator
actor Teacher 
actor User
Administrator --|> Teacher

rectangle "Linguistic Combinatorics" {  
    User -- (Select Language)
    /'доработать: на каждый язык свой бот'/
    (Select Language) ..> (Combinatorics)
    (Select Language) ..> (Listening)
    (Combinatorics) --> (Select Level)
    (Select Level) --> (Сompleting the exercise)
    
    (Teacher)..> (Edit exercise)
    (Administrator) ..> (Edit Language)
    
}
@enduml