@startuml UserCaseMain

actor User
actor Administrator
actor Teacher 

Administrator --|> Teacher

rectangle "Linguistic Combinatorics" {  
    User -- (Select Language)
    note right 
    доработать: на каждый язык свой бот
    end note
    (Select Language) ..> (Combinatorics)
    (Select Language) ..> (Listening)
    (Combinatorics) --> (Select Level)
    (Select Level) --> (Сompleting exercise)
    
    (Teacher)..> (Edit exercise)
    note right
    редактирование осуществляется загрузкой и выгрузкой Excel файла
    end note
    (Administrator) .> (Edit Language)
    (Administrator) .> (Edit User)
    
}
@enduml